### ISSUE TITLE
Examples wanted for the gallery

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1231]
While starting working on the user guide, I noticed that several functions or functionalities are not illustrated in any example of the gallery. Here are a few examples of functionalities that could make nice examples for the gallery (and hence sections of the user guide). Feel free to ask more item to the wishlist in the conversation to follow.
- [x] RGB to HSV conversion, for example for image enhancement (as increasing image saturation), or for image segmentation (in the `data.coffee()` image, a mask of the cup + saucer can be obtained from thresholding the hue channel). WIP: #3607 
-  [x] RGB to gray conversion. Comment on the different weights of the 3 channels, and on the float dtype of the output. 
- [X] gamma and log contrast adjustement. Plot the different kinds of transformations and show the result when applied to a grayscale image such as `moon` DONE: #1670
- [X] Richardson-Lucy deconvolution. DONE: #2376 
- [ ] LPIFilter2D / inverse filters (I have no idea how they are used. @stefanv ?)
- [ ] ``measure.block_reduce``
- [ ] ``measure.profile_line``

**Comment by poyobe** [comment]
I noticed that the rgb2hsv function is used in the "Tinting gray-scale images" example of the gallery. I will try to see if changing the example's title or maybe spliting it in 2 could be a good idea. (Sorry if my english is bad :) )

**Comment by odebeir** [comment]
I volunteer for adding an example for gamma and log contrast adjustment.

**Comment by juliusbierk** [comment]
I'm adding Richardson-Lucy deconvolution to Reconstruction example.

**Comment by souravsingh** [comment]
I will now work on RGB to HSV conversion.

**Comment by emmanuelle** [comment]
@jni I reopened it since I had added one more missing example. Would you prefer that we open a new issue for this?

**Comment by jni** [comment]
Oh yeah I didn't close this on purpose, this was github's auto-closing on merge. Leaving this open is fine by me. =)

**Comment by emmanuelle** [comment]
This issue is quite old now and we have the mini-galleries in the API which help looking for functions without examples. Therefore I'm closing this issue and re-opening a new one targeted at new contributors.
