### ISSUE TITLE
Enhancements and cleanup from NumPy min version bump

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#2203]
With the merge of #2194, **we now depend on NumPy 1.11**. One of the major new features motivating this was the ability to calculate only specific gradients for efficiency. However, since 1.7 there are many new features and other improvements we should take advantage of. 

This Issue will collect and track the progress of multiple different improvements. I'll curate the below list as any additional items/enhancements are brought up. Once we've got all the boxes checked here, at least the low-hanging fruit should be handled. 

## Todo
- [ ] Inspect codebase for uses of `np.gradient` which would benefit from new kwarg
- [ ] Remove `skimage/util/arraypad` and all infrastructure for our internal version of `skimage.util.pad`. Replace all calls with equivalent `np.pad` which is equivalent. Also remove tests. We could alias `np.pad` for API compatibility for some time, though, as this has been publicly exposed.
- [ ] *Additional new NumPy features here as others report them*

**Comment by JDWarner** [comment]
New NumPy features we can now depend on of interest (not an exhaustive list, I just skimmed release notes):

- NumPy 1.8:
  - NaN-safe basic statistics functions added:``nanmean``, ``nanvar``, and ``nanstd`` 
  - `np.full` and `np.full_like` - safer to initialize than `np.empty` which fills with NaNs on some architectures
  - Advanced `np.newaxis` indexing: `array[np.newaxis, [0, 1]]` now a valid form.

- NumPy 1.9:
  - Additional NaN-safe basic statistics functions: `nanmedian` and `nanpercentile`
  - `np.percentile` has an `interplation=` kwarg to select several interpolation methods
  - np.median and np.percentile now support an `axis=` kwarg
  - np.median and np.percentile now have a `keepdims=bool` kwarg which will *retain* the axis in question as a singleton dimension for simpler broadcasting (**very useful**)
  - np.unique now exposes a `unique_counts` parameter

- NumPy 1.10:
  - NaN-safe product: `nanprod`
  - `diagonal` and `diag` functions now return *writeable* views.
  - `np.linalg.multi_dot` added for brevity in linear algebra expressions
  - `np.stack` - combining arrays along a new axis (**lots of potential** to replace `np.concatenate`)
  - `np.cbrt` fast cube roots
  - `np.fft` new `norm=` kwarg potentially of interest

- NumPy 1.11:
  - `np.histogram` has automated bin size estimation available with `bins='auto'` and several specific methods
  - `np.moveaxis` for more control over axis swapping
  - **`SkipTest` and `KnownFailureException` exception classes are exposed in the `numpy.testing` namespace**
  - `np.gradient` now supports `axis=` kwarg
  - `np.testing.assert_warns` can now be used as a context manager

**Comment by soupault** [comment]
NumPy 1.10:
- [ ] new `np.digitize` function (xref https://github.com/scikit-image/scikit-image/issues/1349)

**Comment by hmaarrfk** [comment]
Regarding `stride_tricks`, it seems to be used in two places:
  - The use in [`shape.py`](https://github.com/scikit-image/scikit-image/blob/20ff9a595e907cf2a5fbf14ae31b6654d11fce17/skimage/util/shape.py#L101) doesn't follow broadcasting rules, so `broadcast_to` is not longer applicable.
  - [rag.py](https://github.com/scikit-image/scikit-image/blob/master/skimage/future/graph/rag.py#L155) uses `as_strided` but only requires the arrays to be writable. `broadcast_to` is read only.

**Comment by jni** [comment]
@hmaarrfk the second use has a solution:

```python
>>> import numpy as np
>>> x = np.broadcast_to(1, 4)
>>> x.shape
(4,)
>>> x.strides
(0,)
>>> x.flags.writeable
False
>>> x.flags.writeable = True
>>> x[2] = 3
>>> x
array([3, 3, 3, 3])
```
I'm not sure whether this is more readable than `stride_tricks` is unclear, but I would argue yes.
