### ISSUE TITLE
Modernise build process

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3172]
The build process used to have requirements scattered across many scripts in travis. 
This was probably due to the fact that PyPi didn't have wheels and thus some optimization was done around that.
There seems to have been an attempt at cleaning this up a while back, but the build process is still needlessly complicated.

Many of these are small changes to files, but combined, it can be confusing to understand what happens. I'll try to split them up as different PRs.

 * [x] 0. Ensure that Travis actually fails when the test script fails. 
    -  [x] Master  #3170. 
    -  [x] 0.14.x #3169 

**Everything below needs to be rebased onto 0. to ensure that a new build is actually triggered.**
 * [ ] 4. Move the cythonize script outside of the `skimage` directory. PR #3158.
 * [x] 1. Remove stray pip commands in travis install that don't use a requirements file. PR  #3227
 * [x] 2. Pin all requirements files and not just default.txt  PR #3227
 * [ ] 5. Use `pip install .` to install the package as opposed to calling the setup.py script directly.
    * Since we don't have a wheelhouse anymore, we can ask pip to install all the dependencies listed in the `setup.py` file itself.
    * Will have to use `pytest --pyargs skimage` as opposed to `pytest skimage` since scikit-image isn't installed in development mode anymore.
        * [ ] We install only build dependencies before the build.
 * [x] 6. Consistent Cython versioning: should all require `0.23.4`: PR #3171
 * [x] 7. Improve `build_versions.py` such that it is not hard coded. PR #3211
     * ~~Remove the tools/build_versions.sh script. This functionality is provided by `pip list` and breaks things as we add or remove dependencies.~~ @stefanv made good arguments to keep this scritpt PR #3181
 * [ ] 8. Remove matplotlib as a core dependency: WIP #3129
 * [x] 9. Prefer imageio over PIL (though PIL is still a dependency for tiffle): WIP #3126
 * [x] 10. Reduce the verbosity on the builds as travis is having a hard time keeping up. PR #3182
    * [x] Decrease Python messages
    * [x] run `pytest` without `-v`

Many of these fixes are in #3159, but that PR got too big to handle.

**Comment by hmaarrfk** [comment]
I think this is mostly done. Remains to remove matplotlib as a core dependency. but that has its own PR.
