### ISSUE TITLE
Close old milestones

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#6399]
It looks like some of the scikit-image milestones are already released and this page should be updated:
https://github.com/scikit-image/scikit-image/milestones

In particular, I think you can close:
- [x] 0.17 https://github.com/scikit-image/scikit-image/milestone/15
- [x] 0.17.3 https://github.com/scikit-image/scikit-image/milestone/19 (not released, is there a plan to make a 0.17.3 release?)
- [x] 0.18 https://github.com/scikit-image/scikit-image/milestone/16
- [x] 0.19 https://github.com/scikit-image/scikit-image/milestone/18
- [x] 0.19.1 https://github.com/scikit-image/scikit-image/milestone/20
- [x] 0.19.2 https://github.com/scikit-image/scikit-image/milestone/21

Some of those milestones have open issues / PRs. So you may want to associate them with a future milestone.
